stages:
  - packer
  - docker

packer:
  image: proget-hz.lonsid.cn/masa-images/library/dotnet:6.0
  stage: packer
  only:
    - branches
  script:
    - git clone -b develop https://github.com/BlazorComponent/BlazorComponent.git ./src/BlazorComponent
    - dotnet build src
    - dotnet pack src --include-symbols -p:PackageVersion=0.1.0.$CI_PIPELINE_ID
    - dotnet nuget push "**/*.symbols.nupkg" --source gitlab
  artifacts:
    expire_in: 1 day
    paths:
      - ./src/BlazorComponent

docker:
  image: docker:17.05.0
  stage: docker
  only:
    - branches
  variables:
    DOCKER_HOST: tcp://localhost:2375/
    IMAGE: proget-hz.lonsid.cn/masa-images/library/masa.blazor.docs:0.1.$CI_PIPELINE_ID
  services:
    - name: docker:17.05.0-dind 
      command: ["dockerd-entrypoint.sh","--insecure-registry=proget-hz.lonsid.cn"]
  script:
    - docker login -u gitlabci -p gitlabci http://proget-hz.lonsid.cn
    - docker build -t $IMAGE .
    - docker push $IMAGE
