stages:
  - packer
  - docker
  - deploy-dev
  - deploy-test
  - packer-prd
  - docker-prd
  - deploy-prd

variables:
  IMAGE: registry.cn-hangzhou.aliyuncs.com/masa/masa-blazor-docs:0.2.$CI_PIPELINE_ID

packer:
  image: registry.cn-hangzhou.aliyuncs.com/masa/dotnet_sdk:6.0.100_nodejs14_wasm_v1
  stage: packer
  only:
    - develop 
  script:
    - ls 
    - ls src/
    - node -v
    - dotnet --version
    - git clone -b develop https://github.com/BlazorComponent/BlazorComponent.git ./src/BlazorComponent
    - dotnet build src
    - dotnet pack src --include-symbols -p:PackageVersion=0.2.$CI_PIPELINE_ID
    - dotnet nuget push "**/*.symbols.nupkg" -k $nugetkey -s https://api.nuget.org/v3/index.json
  artifacts:
    expire_in: 1 day
    paths:
      - ./src/BlazorComponent
  retry: 2


docker:
  stage: docker
  tags:
    - linux-shell
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN
  only:
    - branches
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE
    - docker rmi  $IMAGE
  retry: 2

deploy-dev:
  image: portainer/kubectl-shell
  stage: deploy-dev
  only:
    - develop
  script:
    - echo $KUBE_CONFIG_DEV | base64 -d > ./config
    - kubectl --kubeconfig ./config set image deployment/masa-blazor-docs masa-blazor-docs=$IMAGE -n masa-blazor
  retry: 2
  
deploy-test:
  image: portainer/kubectl-shell
  stage: deploy-test
  only:
    - develop
  script:
    - echo $KUBE_CONFIG_DEV | base64 -d > ./config
    - kubectl --kubeconfig ./config set image deployment/masa-blazor-docs masa-blazor-docs=$IMAGE -n test-masa-blazor
  retry: 2

packer-prd:
  image: registry.cn-hangzhou.aliyuncs.com/masa/dotnet_sdk:6.0.100_nodejs14_wasm_v1
  stage: packer-prd
  only:
    - tags 
  script:
    - ls 
    - ls src/
    - node -v
    - dotnet --version
    - git clone -b develop https://github.com/BlazorComponent/BlazorComponent.git ./src/BlazorComponent
    - dotnet workload install wasm-tools
    - dotnet build src
    - dotnet pack src --include-symbols -p:PackageVersion=$CI_COMMIT_TAG
    - dotnet nuget push "**/*.symbols.nupkg" -k $nugetkey -s https://api.nuget.org/v3/index.json
  artifacts:
    expire_in: 1 day
    paths:
      - ./src/BlazorComponent
  retry: 2

docker-prd:
  stage: docker-prd
  tags:
    - linux-shell
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN
  only:
    - tags
  script:
    - docker build -t $IMAGE_PRD .
    - docker push $IMAGE_PRD
  retry: 2

deploy-prd:
  image: portainer/kubectl-shell
  stage: deploy-prd
  only:
    - tags
  script:
    - echo $KUBE_CONFIG_BLAZOR_PRD | base64 -d > ./config
    - kubectl --kubeconfig ./config set image deployment/masa-blazor masa-blazor=$IMAGE_PRD -n masa-blazor
  retry: 2
  when: manual  
