stages:
  - packer
  - docker
  - deploy

variables:
  DOCKER_HOST: tcp://localhost:2375/
  IMAGE: proget-hz.lonsid.cn/masa-images/library/masa.blazor.docs:0.1.$CI_PIPELINE_ID

packer:
  image: proget-hz.lonsid.cn/masa-images/library/dotnet:6.0
  stage: packer
  only:
    - branches
  script:
    - git clone -b develop http://gitlab-hz.lonsid.cn/MASA-Stack/BlazorComponent.git ./src/BlazorComponent
    - dotnet build src
    - dotnet pack src --include-symbols -p:PackageVersion=0.1.0.$CI_PIPELINE_ID
    - dotnet nuget push "**/*.symbols.nupkg" --source gitlab
  artifacts:
    expire_in: 1 day
    paths:
      - ./src/BlazorComponent


docker:
  image: docker:17.05.0
  stage: docker
  only:
    - branches
  services:
    - name: proget-hz.lonsid.cn/masa-images/library/docker:17.05.01-dind
  script:
    - docker login -u gitlabci -p gitlabci http://proget-hz.lonsid.cn
    - docker build -t $IMAGE .
    - docker push $IMAGE

deploy:
  image: zhu1531/rancher
  stage: deploy
  only:
    - branches
  script:
    - rancher kubectl set image deployment/masa-blazor-docs masa-blazor-docs=$IMAGE -n dev-techs-preview
