image: proget-hz.lonsid.cn/masa-images/library/dotnet:5.0

stages:
  - build
  - tests
  - nuget

variables:
  # 拉取 Submodule 内容
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  only:
    - branches
  script:
    - dotnet build src

# tests:
#   stage: tests
#   only:
#     - branches
#   script:
#     - dotnet test --collect:"XPlat Code Coverage"

# nuget:
#   stage: nuget
#   only:
#     - branches
#   script:
#     - dotnet build
#     - dotnet nuget push "**/*.nupkg" --source gitlab
