image: proget-hz.lonsid.cn/masa-images/library/dotnet:6.0

stages:
  - build
  - tests
  - nuget

build:
  stage: build
  only:
    - branches
  script:
    - git clone -b develop https://github.com/BlazorComponent/BlazorComponent.git ./src/BlazorComponent
    - dotnet build src
  artifacts:
    expire_in: 1 day
    paths:
      - .


# tests:
#   stage: tests
#   only:
#     - branches
#   script:
#     - dotnet test --collect:"XPlat Code Coverage"

nuget:
   stage: nuget
   only:
     - branches
   script:
     - dotnet pack src --include-symbols -p:PackageVersion=0.1.0.$CI_PIPELINE_ID
     - dotnet nuget push "**/*.nupkg" --source gitlab

